[colors]
background = '#2533378e'
black = '#253337'
blue = '#3F858E'
cursor = '#c8cccd'
cyan = '#498A92'
foreground = '#c8cccd'
green = '#6F9499'
magenta = '#6B9FA4'
red = '#989A9A'
tabs = '#c8cccd'
tabs-active = '#94A7AA'
white = '#c8cccd'
yellow = '#c8cccd'
dim-black = '#2533378e'
dim-blue = '#3F858E8e'
dim-cyan = '#498A928e'
dim-foreground = '#c8cccd8e'
dim-green = '#6F94998e'
dim-magenta = '#6B9FA48e'
dim-red = '#989A9A8e'
dim-white = '#94A7AA8e'
dim-yellow = '#c8cccd8e'
light-black = '#3F858E'
light-blue = '#498A92'
light-cyan = '#6F9499'
light-foreground = '#6B9FA4'
light-green = '#989A9A'
light-magenta = '#94A7AA'
light-red = '#c8cccd'
light-white = '#3F858E'
light-yellow = '#498A92'
